name: Sparrow-admin-Stg
on:
  push:
    branches:
      - release/2.35.0 
  workflow_dispatch:
    
jobs:
   build:
      runs-on: ubuntu-latest
      environment: sparrow_admin_app_stg
      steps:
         - uses: actions/checkout@master

         - uses: Azure/docker-login@v1
           with:
              login-server: sparrowprod.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker build \
              --build-arg VITE_SPARROW_LAUNCH_URL=${{ vars.VITE_SPARROW_LAUNCH_URL }} \
              --build-arg VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }} \
              --build-arg VITE_LOGIN_REDIRECT=${{ vars.VITE_LOGIN_REDIRECT }} \
              --build-arg VITE_SPARROW_DOCS_URL=${{ vars.VITE_SPARROW_DOCS_URL }} \
              --build-arg VITE_ENVIRONMENT=${{ vars.VITE_ENVIRONMENT }} \
              --build-arg VITE_POSTHOG_CONNECTION_API_KEY=${{ vars.VITE_POSTHOG_CONNECTION_API_KEY }} \
              --build-arg VITE_SPARROW_MARKETING_URL=${{ vars.VITE_SPARROW_MARKETING_URL }} \
              --build-arg VITE_APP_EDITION=${{ vars.VITE_APP_EDITION }} \
              -t sparrowprod.azurecr.io/sparrow-admin-app:${{ github.run_number }} .

              docker push sparrowprod.azurecr.io/sparrow-admin-app:${{ github.run_number }}

   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master
         - uses: richardrigutins/replace-in-files@v1
           with:
              files: "./deployment/deployment.yml"
              search-text: '_BUILD__ID_'
              replacement-text: '${{ github.run_number }}'

         - uses: azure/setup-kubectl@v2.0

         - uses: Azure/k8s-set-context@v2
           with:
              kubeconfig: ${{ secrets.KUBE_CONFIG }}

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              namespace: sparrow-staging
              manifests: |
                 ./deployment/deployment.yml
